### ISSUE TITLE
Does this support running multiple protos?

### ISSUE THREAD

**Issue by d1820** [queil/gmox#6]
From the readme it seems like this can only server up a single proto with a set of responses? Is this correct? And if yes is there an ETA on being able to support many protos and repsonses?

**Comment by queil** [comment]
@d1820 Hi, it should work fine with multiple protos. Have you tried that yet?

**Comment by d1820** [comment]
I have tried just a single so far, and server throws errors

COMMAND
```
 gmox serve --proto ./protos/Test.proto --root ./protos --stub-dir ./stubs
```
```powershell
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:4770
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:4771
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Dev\MockServer\gmox
crit: Microsoft.Extensions.Hosting.Internal.ApplicationLifetime[6]
      An error occurred starting the application
      System.AggregateException: One or more errors occurred. (The node must be of type 'JsonArray'.)
       ---> System.InvalidOperationException: The node must be of type 'JsonArray'.
         at System.Text.Json.Nodes.JsonNode.AsArray()
         at Queil.Gmox.Server.Saturn.configureServices@151-11.Invoke(String path)
         at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
         at Queil.Gmox.Server.Saturn.configureServices@146-10.Invoke(IServiceProvider f, Unit unitVar0)
         at Queil.Gmox.Server.Saturn.configureApp@162-2.Invoke()
         at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
         at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
         at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         --- End of inner exception stack trace ---
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException)
         at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
```

PROTO
```txt
syntax = "proto3";
package Test;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message ChargeType {
   string ChargeTypeId = 1;
   string TenantId = 2;
   string ChargeTypeCode = 3;
   string ChargeTypeDesc = 4;
   string CreateBy = 5;
   .google.protobuf.Timestamp CreateDateTime = 6;
   string LastChangeBy = 7;
   .google.protobuf.Timestamp LastChangeDateTime = 8;
   .google.protobuf.Timestamp RowVersion = 9;
}

message ChargeTypeQueryByCodeRequest {
   string ChargeType = 1;
}

message Error {
   int32 ErrorCode = 1;
   string Message = 2;
   string Domain = 3;
   map<string,string> MetaData = 4;
   int32 RetryDelayInMs = 5;
}

message GrpcChargeTypeListResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   repeated ChargeType Result = 4;
}
message GrpcChargeTypeResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   ChargeType Result = 4;
}
enum StatusCode {
   OK = 0;
   Cancelled = 1;
   Unknown = 2;
   InvalidArgument = 3;
   DeadlineExceeded = 4;
   NotFound = 5;
   AlreadyExists = 6;
   PermissionDenied = 7;
   Unauthenticated = 16;
   ResourceExhausted = 8;
   FailedPrecondition = 9;
   Aborted = 10;
   OutOfRange = 11;
   Unimplemented = 12;
   Internal = 13;
   Unavailable = 14;
   DataLoss = 15;
}
service ChargeTypeGrpcService {
   rpc GetChargeTypeByCode (ChargeTypeQueryByCodeRequest) returns (GrpcChargeTypeResponse);
}

```

MOCK
```
{
  "method": "ChargeTypeGrpcService/GetChargeTypeByCode",
  "match": {
    "exact ": { "chargeType" : "LH" }
  },
  "return": {
    "data": {
      "Status": 0,
      "HasError": false,
      "Error": null,
      "Result": {
        "ChargeTypeId": "e763ff27-acee-471b-b77a-fd40c5b1ded9",
        "TenantId": "12345",
        "ChargeTypeCode": "LH",
        "ChargeTypeDesc": "LINE HAUL",
        "CreateBy": "user",
        "CreateDateTime": "2021-05-12T20:47:08.089927Z",
        "LastChangeBy": "user",
        "LastChangeDateTime": "2021-05-12T20:47:08.089927Z",
        "RowVersion": "2021-05-12T20:47:08.089963Z"
      }
    }
  }
}

REQUEST
```
{
 "chargeType" : "LH"
}
```

**Comment by queil** [comment]
@d1820 your stub file needs to be a JSON array

**Comment by d1820** [comment]
That solved the issue..

I did try multiple protos based on a multi-param concept. Seems like only reads the last paramter of --proto. What is the proper way to supply many protos?

```
gmox serve --proto ./protos/Test.proto --proto ./protos/Test2.proto --root ./protos --stub-dir ./stubs
```

ERROR
```      
An error occurred starting the application
      System.AggregateException: One or more errors occurred. (Method Test.ChargeTypeGrpcService/GetChargeTypeByCode is not available for stubbing. Available methods: Test2.ChargeTypeGrpcService/GetChargeTypeByCode, grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo)
       ---> System.Collections.Generic.KeyNotFoundException: Method Test.ChargeTypeGrpcService/GetChargeTypeByCode is not available for stubbing. Available methods: Test2.ChargeTypeGrpcService/GetChargeTypeByCode, grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
       ---> System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
         at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 677
         at Queil.Gmox.Server.Saturn.configureServices@104-5.Invoke(String methodToFind)
         --- End of inner exception stack trace ---
         at Queil.Gmox.Server.Saturn.configureServices@104-5.Invoke(String methodToFind)
         at Queil.Gmox.Server.Saturn.configureServices@92-3.Invoke(IServiceProvider f, String methodName)
         at Queil.Gmox.Server.Saturn.configureServices@126-8.Invoke(String m)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Queil.Gmox.Server.Saturn.configureServices@124-7.Invoke(String svcMethodName)
         at Queil.Gmox.Server.Saturn.configureServices@133-9.Invoke(IServiceProvider f, JsonNode node)
         at Queil.Gmox.Server.Saturn.configureServices@151-11.Invoke(String path)
         at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
         at Queil.Gmox.Server.Saturn.configureServices@146-10.Invoke(IServiceProvider f, Unit unitVar0)
         at Queil.Gmox.Server.Saturn.configureApp@162-2.Invoke()
         at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
         at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
         at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         --- End of inner exception stack trace ---
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException)
         at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
```

**Comment by queil** [comment]
@d1820 I am on holiday right now but I'll give it a test early next week and fix it if it's broken.

**Comment by queil** [comment]
@d1820 It seems there is a bug. It works in some cases. I need more time to investigate.

**Comment by queil** [comment]
@d1820 Can you please paste your `Test.proto` and `Test2.proto` contents? Also which version of gmox are you running (you can get it by running `gmox version`) ?

**Comment by d1820** [comment]
MockResponse
```
[{
  "method": "Test.ChargeTypeGrpcService/GetChargeTypeByCode",
  "match": {
    "exact": { "ChargeType" : "LH" }
  },
  "return": {
    "data": {
      "Status": 0,
      "HasError": false,
      "Error": null,
      "Result": {
        "ChargeTypeId": "e763ff27-acee-471b-b77a-fd40c5b1ded9",
        "TenantId": "12345",
        "ChargeTypeCode": "LH",
        "ChargeTypeDesc": "LINE HAUL",
        "CreateBy": "user",
        "CreateDateTime": "2021-05-12T20:47:08.089927Z",
        "LastChangeBy": "user",
        "LastChangeDateTime": "2021-05-12T20:47:08.089927Z",
        "RowVersion": "2021-05-12T20:47:08.089963Z"
      }
    }
  }
},
{
  "method": "Test2.ChargeTypeGrpcService/GetChargeTypeByCode",
  "match": {
    "exact": { "ChargeType" : "LH" }
  },
  "return": {
    "data": {
      "Status": 0,
      "HasError": false,
      "Error": null,
      "Result": {
        "ChargeTypeId": "e763ff27-acee-471b-b77a-fd40c5b1ded9",
        "TenantId": "12345",
        "ChargeTypeCode": "LH",
        "ChargeTypeDesc": "LINE HAUL",
        "CreateBy": "user",
        "CreateDateTime": "2021-05-12T20:47:08.089927Z",
        "LastChangeBy": "user",
        "LastChangeDateTime": "2021-05-12T20:47:08.089927Z",
        "RowVersion": "2021-05-12T20:47:08.089963Z"
      }
    }
  }
}]
```

test.proto
```
syntax = "proto3";
package Test;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message ChargeType {
   string ChargeTypeId = 1;
   string TenantId = 2;
   string ChargeTypeCode = 3;
   string ChargeTypeDesc = 4;
   string CreateBy = 5;
   .google.protobuf.Timestamp CreateDateTime = 6;
   string LastChangeBy = 7;
   .google.protobuf.Timestamp LastChangeDateTime = 8;
   .google.protobuf.Timestamp RowVersion = 9;
}

message ChargeTypeQueryByCodeRequest {
   string ChargeType = 1;
}

message Error {
   int32 ErrorCode = 1;
   string Message = 2;
   string Domain = 3;
   map<string,string> MetaData = 4;
   int32 RetryDelayInMs = 5;
}

message GrpcChargeTypeListResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   repeated ChargeType Result = 4;
}
message GrpcChargeTypeResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   ChargeType Result = 4;
}
enum StatusCode {
   OK = 0;
   Cancelled = 1;
   Unknown = 2;
   InvalidArgument = 3;
   DeadlineExceeded = 4;
   NotFound = 5;
   AlreadyExists = 6;
   PermissionDenied = 7;
   Unauthenticated = 16;
   ResourceExhausted = 8;
   FailedPrecondition = 9;
   Aborted = 10;
   OutOfRange = 11;
   Unimplemented = 12;
   Internal = 13;
   Unavailable = 14;
   DataLoss = 15;
}
service ChargeTypeGrpcService {
   rpc GetChargeTypeByCode (ChargeTypeQueryByCodeRequest) returns (GrpcChargeTypeResponse);
}

```

test2.proto
```
syntax = "proto3";
package Test2;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message ChargeType {
   string ChargeTypeId = 1;
   string TenantId = 2;
   string ChargeTypeCode = 3;
   string ChargeTypeDesc = 4;
   string CreateBy = 5;
   .google.protobuf.Timestamp CreateDateTime = 6;
   string LastChangeBy = 7;
   .google.protobuf.Timestamp LastChangeDateTime = 8;
   .google.protobuf.Timestamp RowVersion = 9;
}

message ChargeTypeQueryByCodeRequest {
   string ChargeType = 1;
}

message Error {
   int32 ErrorCode = 1;
   string Message = 2;
   string Domain = 3;
   map<string,string> MetaData = 4;
   int32 RetryDelayInMs = 5;
}

message GrpcChargeTypeListResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   repeated ChargeType Result = 4;
}
message GrpcChargeTypeResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   ChargeType Result = 4;
}
enum StatusCode {
   OK = 0;
   Cancelled = 1;
   Unknown = 2;
   InvalidArgument = 3;
   DeadlineExceeded = 4;
   NotFound = 5;
   AlreadyExists = 6;
   PermissionDenied = 7;
   Unauthenticated = 16;
   ResourceExhausted = 8;
   FailedPrecondition = 9;
   Aborted = 10;
   OutOfRange = 11;
   Unimplemented = 12;
   Internal = 13;
   Unavailable = 14;
   DataLoss = 15;
}
service ChargeTypeGrpcService {
   rpc GetChargeTypeByCode (ChargeTypeQueryByCodeRequest) returns (GrpcChargeTypeResponse);
}

```

**Comment by queil** [comment]
@d1820 Ok, I think I found the problem. I was able to successfully run the provided files with the following command:
```
gmox serve --proto .\protos\Test.proto .\protos\Test2.proto  --root .\protos --stub-dir .\stubs
```
Can you try that?

I.e. you do not need to specify `--proto` twice. I'll make `--proto` a unique parameter so the CLI fails if you pass it twice.

**Comment by d1820** [comment]
Awesome! that did it.. Thanks for all the help
